/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/bookings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Предстоящие встречи по всем типам событий одним списком, отсортированные по
         *     возрастанию `start`. Страница владельца.
         */
        get: operations["Bookings_list"];
        put?: never;
        /**
         * @description Создает бронирование гостя на выбранный свободный слот.
         *
         *     Возвращает 400, если типа события не существует (`event_type_not_found`),
         *     `start` не совпадает с началом слота (`slot_not_available`) или выходит за
         *     окно записи (`outside_booking_window`); 409, если на это время уже есть
         *     бронирование любого типа события (`slot_taken`).
         */
        post: operations["Bookings_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Список типов событий. Используется и владельцем, и публичной страницей
         *     видов брони.
         */
        get: operations["EventTypes_list"];
        put?: never;
        /** @description Создает тип события. Идентификатор задает владелец. */
        post: operations["EventTypes_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Возвращает тип события по идентификатору. */
        get: operations["EventTypes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/event-types/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * @description Свободные слоты выбранного типа события в окне записи: 14
         *     дней, начиная с текущей даты. Слоты отсортированы по возрастанию `start`.
         */
        get: operations["EventTypes_listSlots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/owner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Возвращает заранее заданный профиль владельца календаря. */
        get: operations["OwnerProfile_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Тело ответа при ошибке. */
        ApiError: {
            /** @description Машиночитаемый код ошибки. */
            code: components["schemas"]["ErrorCode"];
            /** @description Человекочитаемое описание ошибки. */
            message: string;
        };
        /** @description Бронирование, созданное гостем на конкретный слот. */
        Booking: {
            /** @description Идентификатор бронирования. Назначается сервером. */
            id: string;
            /** @description Идентификатор забронированного типа события. */
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Начало встречи, UTC.
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец встречи, UTC. Равен `start` плюс `durationMinutes` типа события.
             */
            end: string;
            /** @description Имя гостя. */
            guestName: string;
            /**
             * Format: email
             * @description Email гостя.
             */
            guestEmail: string;
            /**
             * Format: date-time
             * @description Момент создания бронирования, UTC.
             */
            createdAt: string;
        };
        /** @description Данные, которые гость отправляет для создания бронирования. */
        BookingCreate: {
            /** @description Идентификатор выбранного типа события. */
            eventTypeId: string;
            /**
             * Format: date-time
             * @description Начало выбранного свободного слота, UTC.
             */
            start: string;
            /** @description Имя гостя. */
            guestName: string;
            /**
             * Format: email
             * @description Email гостя.
             */
            guestEmail: string;
        };
        /**
         * @description Машиночитаемые коды ошибок. Клиент принимает решения по `code`, а не по
         *     тексту `message`.
         * @enum {string}
         */
        ErrorCode: "validation_failed" | "event_type_not_found" | "event_type_id_taken" | "slot_not_available" | "outside_booking_window" | "slot_taken";
        /** @description Тип события, который владелец предлагает гостям для бронирования. */
        EventType: {
            /** @description Идентификатор типа события. Задается владельцем при создании. */
            id: string;
            /** @description Название типа события. Показывается гостю на странице видов брони. */
            title: string;
            /** @description Описание типа события. Показывается гостю на странице видов брони. */
            description: string;
            /**
             * Format: int32
             * @description Длительность встречи в минутах.
             */
            durationMinutes: number;
        };
        /** @description Владелец календаря — единственный заранее заданный профиль. */
        Owner: {
            /** @description Идентификатор владельца. */
            id: string;
            /** @description Отображаемое имя владельца. */
            name: string;
        };
        /**
         * @description Свободный интервал в окне записи, на который гость может создать бронирование.
         *     Слоты, пересекающиеся с любым существующим бронированием, свободными не
         *     считаются и в выдачу не попадают.
         */
        Slot: {
            /**
             * Format: date-time
             * @description Начало слота, UTC.
             */
            start: string;
            /**
             * Format: date-time
             * @description Конец слота, UTC. Равен `start` плюс `durationMinutes` типа события.
             */
            end: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Bookings_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"][];
                };
            };
        };
    };
    Bookings_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCreate"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Booking"];
                };
            };
            /**
             * @description Данные запроса не проходят валидацию либо противоречат правилам бронирования.
             *     Коды: `validation_failed`, `event_type_not_found`, `slot_not_available`,
             *     `outside_booking_window`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /**
             * @description Запрос конфликтует с текущим состоянием: тип события с таким `id` уже есть
             *     либо выбранное время занято другим бронированием.
             *     Коды: `event_type_id_taken`, `slot_taken`.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"][];
                };
            };
        };
    };
    EventTypes_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventType"];
            };
        };
        responses: {
            /** @description The request has succeeded and a new resource has been created as a result. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /**
             * @description Данные запроса не проходят валидацию либо противоречат правилам бронирования.
             *     Коды: `validation_failed`, `event_type_not_found`, `slot_not_available`,
             *     `outside_booking_window`.
             */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
            /**
             * @description Запрос конфликтует с текущим состоянием: тип события с таким `id` уже есть
             *     либо выбранное время занято другим бронированием.
             *     Коды: `event_type_id_taken`, `slot_taken`.
             */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventType"];
                };
            };
            /** @description Запрошенный ресурс не найден. Код: `event_type_not_found`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    EventTypes_listSlots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Slot"][];
                };
            };
            /** @description Запрошенный ресурс не найден. Код: `event_type_not_found`. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiError"];
                };
            };
        };
    };
    OwnerProfile_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Owner"];
                };
            };
        };
    };
}
